# Generated by Django 3.2.2 on 2021-05-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
